### ISSUE TITLE
@rytilahti: Home Assistant asks you to fix your GitHub account!

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/people#10]
Hi @rytilahti - you're a member of [Home Assistant](https://github.com/home-assistant)'s organisation on GitHub, but our audit-bot has noticed your GitHub account isn't fully set up to meet the standards we need.

If you're no longer supposed to be a member of the organisation, please use your [GitHub organisation settings](https://github.com/settings/organizations) page to leave.

Otherwise, we just need you to help us with a few things to keep our code safe and secure on GitHub:

* Get a pull request opened to add your username to our [users.txt](https://github.com/home-assistant/people/blob/master/users.txt) file _- ideally, a Tech Lead or Dev Manager at Home Assistant should open this request for you_.

You have a limited amount of time to fix these issues, otherwise you'll be automatically removed from this organisation.

Thanks for helping us out - it makes our lives a lot easier, and help keeps our code secure!

**Comment by rytilahti** [comment]
Hi @robbiet480, I have a couple of questions:

1) Is there some sort of explanation/write-up about the standards? 
2) I suppose the only problem in my case is the missing entry in users.txt (that file seems to be quite sparse, what/how is it going to be used and how it makes it all safer?

Thanks!

**Comment by robbiet480** [comment]
Reopening, bot will close automatically in the next few days.

@rytilahti I wrote a pretty detailed explanation of what this is [here](https://github.com/home-assistant/people/issues/68#issuecomment-479416612), lmk if you still have questions.

**Comment by rytilahti** [comment]
@robbiet480 thanks, sounds good!

**Comment by robbiet480** [comment]
Thanks for fixing those requirements (ie Sponsor).  Closing this issue, you're good to go! :sparkles:

**Comment by robbiet480** [comment]
Thanks for fixing those requirements (ie Sponsor).  Closing this issue, you're good to go! :sparkles:
