### ISSUE TITLE
@mjrider: Home Assistant asks you to fix your GitHub account!

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/people#68]
Hi @mjrider - you're a member of [Home Assistant](https://github.com/home-assistant)'s organisation on GitHub, but our audit-bot has noticed your GitHub account isn't fully set up to meet the standards we need.

If you're no longer supposed to be a member of the organisation, please use your [GitHub organisation settings](https://github.com/settings/organizations) page to leave.

Otherwise, we just need you to help us with a few things to keep our code safe and secure on GitHub:

* Get a pull request opened to add your username to our [users.txt](https://github.com/home-assistant/people/blob/master/users.txt) file _- ideally, a Tech Lead or Dev Manager at Home Assistant should open this request for you_.

You have a limited amount of time to fix these issues, otherwise you'll be automatically removed from this organisation.

Thanks for helping us out - it makes our lives a lot easier, and help keeps our code secure!

**Comment by mjrider** [comment]
Could you please explain why, because adding my name to this repo is something you could have done without my help

**Comment by robbiet480** [comment]
@mjrider Sure thing!

1. The reason we are doing this is to weed out those that are no longer actively contributing to the project without requiring a human (read: me) to manually investigate each and every users commit history _across **all** of our repositories_. I think you can understand that I, nor anyone else, wants to audit all 84 contributors that currently hold access across one or more of our 62 repositories. I don't want to spend my time like that, do you? 
2. Once we have the actually active contributors in `users.txt`, I will be able to enable the secondary level of this tool, automatic assurance that only people that are actively vouched for have access to our repositories.
3. The notice of random audit and removal and my authority to do so was originally [published January 21, 2017 in our governance update](https://www.home-assistant.io/blog/2017/01/21/home-assistant-governance/#security-requirements), something that I had hoped all developers had previously read as all developers implicitly agreed to it by submitting code that falls under our Code of Conduct and Contributors License Agreement. That document does not specify the manner in which an audit will be done, so it's really left up to the person running the audit to decide how to do one. I've decided on this new system, because while I care about security, I don't care to spend hours manually auditing GitHub users.

If you are still unhappy and/or unwilling to follow these simple instructions that should take 60 seconds at worst, that's fine, just know the bot will automatically remove you within the next few days from the Home Assistant organization. You will not be able to be re-added to the organization moving forward without having an entry in users.txt.

Thanks so much for reading and being a Home Assistant contributor!

**Comment by mjrider** [comment]
no, i don't have a problem with adding my name to a list or auditing users.

The problem i had, was the text of the issue missing information. And in a strict reading even instructed my to do nothing about it.
> ideally, a Tech Lead or Dev Manager at Home Assistant should open this request for you.

asking +75 person to edit the same file at the same time, without instructions about things like keeping the list sorted or not is also a bit troublesome.

**Comment by robbiet480** [comment]
The text of the issue still referencing "tech lead or dev manager" was a minor oversight on my part. As for sorting, I already have plans to add a status check on every PR after this initial wave to ensure the list remains sorted, but didn't have time to do so tonight, nor did I want to have everyone have to deal with alphabetizing now due to possibility of frequent merge conflicts.

Thanks for your understanding and your PR, this issue will automatically close in the next day or two.

**Comment by robbiet480** [comment]
Thanks for fixing those requirements (ie Sponsor).  Closing this issue, you're good to go! :sparkles:

**Comment by robbiet480** [comment]
Thanks for fixing those requirements (ie Sponsor).  Closing this issue, you're good to go! :sparkles:
